# Generated by Django 4.2.5 on 2023-09-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khata_book',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='khata_book',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='khata_book',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
