# Generated by Django 4.2.5 on 2023-09-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khata_app', '0003_khata_book_created_on_khata_book_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khata_book',
            old_name='total_price',
            new_name='total_amount',
        ),
    ]
