# Generated by Django 4.2.5 on 2023-09-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata_app', '0005_alter_khata_book_created_on_alter_khata_book_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khata_book',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
